# PRISM DATA CHECK (Before any preprocessing)
* check the perturbation name, ntc labeling, CRISPR type, var name and etc.

In [1]:
import scanpy as sc

In [2]:
DIR = "/mnt/nas2/projects/vcc-data/PRISM/Datasets/"

### GSE210681
* control label: `non-targeting`
* perturbation column: `perturbation_name` on `obs`
* CRISPR type: only CRISPRi
* Double perturbation: X

In [3]:
GSE210681 = sc.read_h5ad(DIR+"GSE210681.h5ad", backed = "r")
GSE210681.obs.head()

/home/dev02/miniconda3/envs/prophet_env/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

,perturbation_name,guide_sequence,n_guides,batch,organism,organ,cell_type,condition,crispr_type,cancer_type,total_counts,n_genes_by_counts
AAACCCAAGAATCCCT-1,PYROXD1,GCGGCGGAGCAACGGGACTC,1,GSM6435418_scRNAseq_2kG_2PMDox2_3,Humans (Homo sapiens),Endothelial Cells,Endothelial Cells,test,CRISPRi,Non-cancer,17116.0,4142
AAACCCAAGACCATTC-1,EPHA2,GGGCGTTGGTGACGTCACGC,1,GSM6435418_scRNAseq_2kG_2PMDox2_3,Humans (Homo sapiens),Endothelial Cells,Endothelial Cells,test,CRISPRi,Non-cancer,19615.0,4332
AAACCCAAGACGATAT-1,non-targeting,No_Guide,1,GSM6435418_scRNAseq_2kG_2PMDox2_3,Humans (Homo sapiens),Endothelial Cells,Endothelial Cells,control,CRISPRi,Non-cancer,8952.0,2799
AAACCCAAGCAGATAT-1,non-targeting,No_Guide,1,GSM6435418_scRNAseq_2kG_2PMDox2_3,Humans (Homo sapiens),Endothelial Cells,Endothelial Cells,control,CRISPRi,Non-cancer,7678.0,2570
AAACCCAAGCCGCACT-1,non-targeting,No_Guide,1,GSM6435418_scRNAseq_2kG_2PMDox2_3,Humans (Homo sapiens),Endothelial Cells,Endothelial Cells,control,CRISPRi,Non-cancer,7670.0,2326

In [22]:
GSE210681[GSE210681.obs.condition == "control"].obs.perturbation_name.unique()

['non-targeting']
Categories (1, object): ['non-targeting']

In [4]:
GSE210681.obs.crispr_type.value_counts()

crispr_type
CRISPRi    794783
Name: count, dtype: int64

### GSE221321
* control label: `non-targeting`
* perturbation column: `perturbation_name` on `obs`
* CRISPR type: `CRISPRi` + `CRISPR KO`
* Double perturbation: O

In [5]:
GSE221321 = sc.read_h5ad(DIR+"GSE221321.h5ad", backed = "r")
GSE221321.obs.head()

/home/dev02/miniconda3/envs/prophet_env/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

,Total_RNA_count,Total_unique_genes,10X_channel,Percent_mitochondrial_reads,Guides,Guides_collapsed_by_gene,Total_number_of_guides,S_score,G2M_score,Cell_cycle_phase,perturbation_name,condition,n_guides,crispr_type,cancer_type,cell_type,organism
AAACCCAAGAGTGACC-1,2413.0,1278,Normal_1,5.719022,TNFRSF11A_TTTGTGGCACTGGATCAATG_CRISPRko--STK4-...,TNFRSF11A--STK4-AS1,2.0,-0.072268,-0.068220,G1,TNFRSF11A+STK4-AS1,test,2,CRISPR KO,Leukemia,THP-1 cell,Humans (Homo sapiens)
AAACCCACACAGGATG-1,9174.0,2666,Normal_1,5.646392,GSDMC_GGAGCATCCATGGTCCACAG_CRISPRko--LRP1B_TGC...,GSDMC--LRP1B,2.0,-0.091449,-0.078500,G1,GSDMC+LRP1B,test,2,CRISPR KO,Leukemia,THP-1 cell,Humans (Homo sapiens)
AAACCCACACCTCTAC-1,3779.0,1864,Normal_1,6.086266,NFATC2_GCGGAGGCATTCGTGCGCCG_CRISPRko--TAB3_AAA...,NFATC2--TAB3,2.0,0.341332,0.082301,S,NFATC2+TAB3,test,2,CRISPR KO,Leukemia,THP-1 cell,Humans (Homo sapiens)
AAACCCACATTGCCGG-1,9882.0,2892,Normal_1,4.604331,TXNDC17_CTGAACCAGTCGTACGAGAG_CRISPRko,TXNDC17,1.0,0.034257,-0.086085,S,TXNDC17,test,1,CRISPR KO,Leukemia,THP-1 cell,Humans (Homo sapiens)
AAACCCAGTCATCACA-1,10399.0,2514,Normal_1,3.413790,TNFSF11_CGTGGCTCGGAGGAGATGGG_CRISPRko,TNFSF11,1.0,-0.012602,-0.122855,G1,TNFSF11,test,1,CRISPR KO,Leukemia,THP-1 cell,Humans (Homo sapiens)

In [23]:
GSE221321[GSE221321.obs.condition == "control"].obs.perturbation_name.unique()

['non-targeting']
Categories (1, object): ['non-targeting']

In [6]:
GSE221321.obs.crispr_type.value_counts()

crispr_type
CRISPR KO    119656
CRISPRi       90475
Name: count, dtype: int64

### GSE208240
* control label: `control` at `obs.condition`
* perturbation column: `perturbation_name` on `obs`
* CRISPR type: `CRISPRi` ONLY 
* Double perturbation: O

In [7]:
GSE208240 = sc.read_h5ad(DIR+"GSE208240.h5ad", backed = "r")
GSE208240.obs.head()

,perturbation_name,condition,targeting,guide_identity,number_of_guides,organism,cell_type,crispr_type,cancer_type
barcode,,,,,,,,,
AAACCTGAGAAACCTA-1,BCKDK + EIF2AK3,test,Targeting,BCKDK_+_31119819.23-P1P2_CR3-cs1;EIF2AK3_-_889...,2,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
AAACCTGAGAATTCCC-1,COG6 + SIGMAR1 + TMEM97,test,Targeting,COG6_-_40229866.23-P1P2_CR3-cs1;SIGMAR1_+_3463...,3,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
AAACCTGAGCCGATTT-1,EIF2AK2 + STK16,test,Targeting,EIF2AK2_+_37384079.23-P1P2_CR1-cs1;STK16_+_220...,3,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
AAACCTGAGCGAGAAA-1,AP3B1 + CCZ1 + EIF3F + RBX1,test,Targeting,AP3B1_-_77590427.23-P1P2_CR1-cs1;CCZ1_-_593859...,4,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
AAACCTGAGGTGCTTT-1,TRMT1,test,Targeting,TRMT1_-_13227169.23-P1P2_CR3-cs1,1,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer

In [8]:
GSE208240.obs.crispr_type.value_counts()

crispr_type
CRISPRi    73989
Name: count, dtype: int64

In [9]:
GSE208240.obs.condition.value_counts()

condition
test       59674
control    14315
Name: count, dtype: int64

In [10]:
GSE208240.obs.targeting.value_counts()

targeting
Targeting        59674
Non-targeting    14315
Name: count, dtype: int64

In [24]:
GSE208240[GSE208240.obs.condition == "control"].obs.perturbation_name.unique()

['BECN1 + EMC2 + GOLGA7 + KPNA2 + MBTPS2 + RAB7..., 'ACE2 + non-targeting', 'ASNA1 + BCL2L1 + CDK6 + CKM + COG6 + CTSB + E..., 'CNBP + VPS39 + non-targeting', 'non-targeting', ..., 'CDK6 + HDAC2 + STAT2 + TMPRSS2 + non-targeting', 'CNBP + MARK2 + non-targeting', 'IFITM1 + RIPK1 + non-targeting', 'CHEK2 + SKIV2L + TBKBP1 + non-targeting', 'BAX + CCZ1B + COG5 + non-targeting']
Length: 5958
Categories (5958, object): ['ACE2 + ADCK4 + ANPEP + ATG14 + BCL2 + BRD4 + ..., 'ACE2 + ADCK4 + ARF1 + CASP8 + CCZ1B + ERN1 + ..., 'ACE2 + ADCK4 + ARFRP1 + B3GALT6 + BRD4 + CNBP..., 'ACE2 + ADCK4 + ATF6 + BAX + BCL2L1 + CWC27 + ..., ..., 'ZCRB1 + non-targeting', 'ZDHHC5 + non-targeting', 'ZYG11B + non-targeting', 'non-targeting']

In [11]:
GSE208240[GSE208240.obs.condition == "control"].obs

,perturbation_name,condition,targeting,guide_identity,number_of_guides,organism,cell_type,crispr_type,cancer_type
barcode,,,,,,,,,
AAACCTGGTGATGTGG-1,BECN1 + EMC2 + GOLGA7 + KPNA2 + MBTPS2 + RAB7A...,control,Non-targeting,EMC2_+_109455869.23-P1P2_CR3-cs1;MBTPS2_-_2185...,16,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
AAACGGGAGAATAGGG-1,ACE2 + non-targeting,control,Non-targeting,ACE2_-_15619013.23-P1P2_CR3-cs1;non-targeting_...,2,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
AAACGGGAGTCACGCC-1,ASNA1 + BCL2L1 + CDK6 + CKM + COG6 + CTSB + EI...,control,Non-targeting,COG6_+_40230096.23-P1P2_CR1-cs1;BCL2L1_-_30310...,15,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
AAACGGGCACATCCAA-1,CNBP + VPS39 + non-targeting,control,Non-targeting,non-targeting_02254_CR1-cs1;VPS39_-_42500464.2...,3,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
AAACGGGCATCACGAT-1,non-targeting,control,Non-targeting,non-targeting_02521_CR3-cs1,1,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
...,...,...,...,...,...,...,...,...,...
TTTGGTTGTCTCGTTC-8,non-targeting,control,Non-targeting,non-targeting_00024_CR3-cs1;non-targeting_0306...,2,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
TTTGGTTGTGAGTATA-8,RNF41 + non-targeting,control,Non-targeting,RNF41_-_56615654.23-P1P2_CR3-cs1;non-targeting...,4,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
TTTGGTTTCACCCTCA-8,PPIA + non-targeting,control,Non-targeting,non-targeting_01725_CR3-cs1;PPIA_+_44836665.23...,2,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
TTTGTCAGTCTCTTTA-8,BAX + CCZ1B + COG5 + non-targeting,control,Non-targeting,COG5_+_107204333.23-P1P2_CR1-cs1;COG5_+_107204...,8,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer
TTTGTCAGTTTGACAC-8,CDK6 + HDAC2 + STAT2 + TMPRSS2 + non-targeting,control,Non-targeting,TMPRSS2_-_42879996.23-P1P2_CR3-cs1;STAT2_+_567...,6,Homo sapiens,Lung epithelial cells,CRISPRi,Lung Cancer

### GSE150062
* control label: `non-targeting`
* perturbation column: `perturbation_name` on `obs`
* CRISPR type: `CRISPRi` ONLY 
* Double perturbation: X

In [12]:
GSE150062 = sc.read_h5ad(DIR+"GSE150062.h5ad", backed="r")
GSE150062.obs.head()

,orig.ident,nCount_RNA,nFeature_RNA,nCount_grna,nFeature_grna,sample,condition,UMI_count,z_score,guide,...,low_res_cluster,trajectory,library,primary_pheno,diff_pheno,diff_hit_direction,cell_type,organism,crispr_type,cancer_type
AAACGAATCAGACCGC-1_1,diff_1,22521,5346,69,19,diff_1,test,45,1.088537,sgLH02412_1,...,9,Cell Cycle,lncRNA,NaN,-0.235598,Non-hit,iPSCs (induced pluripotent stem cells),Humans (Homo sapiens),CRISPRi,non-cancer
AAAGGGCCAGAGAATT-1_1,diff_1,15066,3902,426,11,diff_1,test,407,1.269091,sgIMMP1L_1,...,4,NSC,Coding,Differentiation,1.925859,Positive Hit,iPSCs (induced pluripotent stem cells),Humans (Homo sapiens),CRISPRi,non-cancer
AAAGGGCCATGAGAAT-1_1,diff_1,20844,5095,670,16,diff_1,test,649,0.908249,sgPCGF2_1,...,4,NSC,Coding,Differentiation,2.117745,Positive Hit,iPSCs (induced pluripotent stem cells),Humans (Homo sapiens),CRISPRi,non-cancer
AAAGTCCCATGGCACC-1_1,diff_1,14015,4028,820,13,diff_1,test,805,1.661506,sgWNT5B_1,...,9,Cell Cycle,Coding,NaN,-0.058791,Non-hit,iPSCs (induced pluripotent stem cells),Humans (Homo sapiens),CRISPRi,non-cancer
AAAGTCCTCGAGTACT-1_1,diff_1,34393,6566,535,14,diff_1,test,518,0.757062,sgAMBRA1_2,...,7,Non-NSC,Coding,Dual,0.877920,Positive Hit,iPSCs (induced pluripotent stem cells),Humans (Homo sapiens),CRISPRi,non-cancer

In [13]:
GSE150062.obs.perturbation_name

AAACGAATCAGACCGC-1_1    LH02412
AAAGGGCCAGAGAATT-1_1     IMMP1L
AAAGGGCCATGAGAAT-1_1      PCGF2
AAAGTCCCATGGCACC-1_1      WNT5B
AAAGTCCTCGAGTACT-1_1     AMBRA1
                         ...
TTGATGGGTTCCAGGC-1_6      MED24
TTGGGCGAGGCTGAAC-1_6       PAF1
TTGTTTGCACTAGGCC-1_6    LH13772
TTGTTTGTCGCCTTGT-1_6     IL17RD
TTTATGCGTCTGATAC-1_6    LH04660
Name: perturbation_name, Length: 78393, dtype: category
Categories (241, object): ['AEBP2', 'AMBRA1', 'AMER1', 'APC', ..., 'ZMYM5', 'ZNF385A', 'ZNF551', 'non-targeting']

In [14]:
GSE150062.obs.crispr_type.value_counts()

crispr_type
CRISPRi    78393
Name: count, dtype: int64

In [25]:
GSE150062[GSE150062.obs.condition == "control"].obs.perturbation_name.unique()

['non-targeting']
Categories (1, object): ['non-targeting']

### GSE261283
* control label: `non-targeting`
* perturbation column: `perturbation_name` on `obs`
* CRISPR type: `CRISPRi` ONLY 
* Double perturbation: O

In [15]:
GSE261283 = sc.read_h5ad(DIR+"GSE261283.h5ad", backed="r")
GSE261283.obs.head()

/home/dev02/miniconda3/envs/prophet_env/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

,Pool,n_genes_by_counts,pct_counts_mt,total_counts,total_counts_mt,num_features,feature_call,num_umis,perturbation_name,crispr_type,cancer_type,cell_type,organism,condition
barcode,,,,,,,,,,,,,,
AAACCCAAGAAGCGGG-1,0,5729,3.017132,19787,597,1,rs1919873_4,268,GJA1,CRISPRi,non-cancer,human fetal osteoblast 1.19 cells (hFOBs),Humans (Homo sapiens),test
AAACCCAAGCCTGAAG-8,6,8513,5.231251,54270,2839,2,rs57246313_1|rs2332323_5,1041|4078,HOXA9+CBLN3+KHNYN+RABGGTA+SDR39U1,CRISPRi,non-cancer,human fetal osteoblast 1.19 cells (hFOBs),Humans (Homo sapiens),test
AAACCCAAGCTTACGT-8,6,7215,2.489260,40735,1014,1,rs10792352_2,368,AHNAK,CRISPRi,non-cancer,human fetal osteoblast 1.19 cells (hFOBs),Humans (Homo sapiens),test
AAACCCAAGGATTTGA-1,0,4444,6.514528,15074,982,1,rs4671647_5,560,SPRED2,CRISPRi,non-cancer,human fetal osteoblast 1.19 cells (hFOBs),Humans (Homo sapiens),test
AAACCCAAGGTACAAT-7,5,7309,2.860941,39113,1119,1,rs2332323_1,15,CBLN3+KHNYN+RABGGTA+SDR39U1,CRISPRi,non-cancer,human fetal osteoblast 1.19 cells (hFOBs),Humans (Homo sapiens),test

In [16]:
GSE261283.obs.crispr_type.value_counts()

crispr_type
CRISPRi    33038
Name: count, dtype: int64

In [26]:
GSE261283[GSE261283.obs.condition == "control"].obs.perturbation_name.unique()

['non-targeting']
Categories (1, object): ['non-targeting']

### GSE165291
* control label: `control` at `obs.condition`
* perturbation column: `perturbation_name` on `obs`
* CRISPR type: `CRISPRi`, `CRISPRn` 
* Double perturbation: X

In [17]:
GSE165291 = sc.read_h5ad(DIR+"GSE165291.h5ad", backed="r")
GSE165291.obs.head()

/home/dev02/miniconda3/envs/prophet_env/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

,guide_identity,read_count,UMI_count,coverage,gemgroup,good_coverage,number_of_cells,sample,cancer_type,cell_type,organism,perturbation_name,condition,crispr_type
cell_barcode,,,,,,,,,,,,,,
AAACCTGAGAACTCGG-3,TRAPPC11_pMH2062,1332,86,15.488372,3,True,1,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),TRAPPC11,test,CRISPRi
AAACCTGAGAAGAAGC-4,STAT2_pMH2128,337,46,7.326087,4,True,1,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),STAT2,test,CRISPRi
AAACCTGAGAAGGCCT-2,STAT2_pMH2128,1162,72,16.138889,2,True,1,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),STAT2,test,CRISPRi
AAACCTGAGACACGAC-3,CASP9_pMH2178,1427,97,14.711340,3,True,1,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),CASP9,test,CRISPRi
AAACCTGAGAGAACAG-4,HCCS_pMH2186,397,48,8.270833,4,True,2,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),HCCS,test,CRISPRi

In [18]:
GSE165291.obs.condition.unique()

['test', 'control']
Categories (2, object): ['control', 'test']

In [19]:
GSE165291[GSE165291.obs.condition == 'control'].obs

,guide_identity,read_count,UMI_count,coverage,gemgroup,good_coverage,number_of_cells,sample,cancer_type,cell_type,organism,perturbation_name,condition,crispr_type
cell_barcode,,,,,,,,,,,,,,
AAACCTGGTTGGTAAA-1,*,1,1,1.000000,1,False,0,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),NaN,control,CRISPRi
AAAGCAAAGCTAACAA-2,*,3,3,1.000000,2,False,0,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),NaN,control,CRISPRi
AAAGTAGCACGCTTTC-3,*,2,2,1.000000,3,False,0,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),NaN,control,CRISPRi
AAAGTAGTCAAGCCTA-4,*,2,2,1.000000,4,False,0,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),NaN,control,CRISPRi
AAATGCCCAATGGACG-1,*,4,3,1.333333,1,False,0,host,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),NaN,control,CRISPRi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCAGTCCGCTGA-3,*,597,20,29.850000,3,True,2,host_and_virus,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),NaN,control,CRISPRn
TTTGTCAGTCGGATCC-3,control_human_AAVS1_pMH2520,1015,46,22.065217,3,True,1,host_and_virus,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),AAVS1,control,CRISPRn
TTTGTCATCCACGAAT-3,control_HCMV_US11-US12_pMH2518,1320,46,28.695652,3,True,1,host_and_virus,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),US11-US12,control,CRISPRn
TTTGTCATCCATGCTC-4,control_human_H11_pMH2524,1008,29,34.758621,4,True,2,host_and_virus,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),H11,control,CRISPRn
TTTGTCATCGTTACAG-1,control_HCMV_US6-US7_pMH2512,934,47,19.872340,1,True,2,host_and_virus,non-cancer,human foreskin fibroblasts (HFFs),Humans (Homo sapiens),US6-US7,control,CRISPRn

In [20]:
GSE165291.obs.perturbation_name.value_counts()

perturbation_name
RBBP5       2791
RGP1        2302
SLC35B2     2203
IFNAR2      2002
HS6ST1      1996
            ...
CLYBL        374
RBX1         368
US9-US10     333
AAVS1        314
TIGRE        228
Name: count, Length: 95, dtype: int64

In [27]:
GSE165291[GSE165291.obs.condition == "control"].obs.perturbation_name.unique()

[NaN, 'CLYBL', 'US11-US12', 'US6-US7', 'US3-US6', 'AAVS1', 'H11', 'TIGRE', 'US9-US10']
Categories (8, object): ['AAVS1', 'CLYBL', 'H11', 'TIGRE', 'US3-US6', 'US6-US7', 'US9-US10', 'US11-US12']

In [31]:
unique_list = GSE165291[GSE165291.obs.condition == "control"].obs.perturbation_name.unique()
for l in unique_list:
    print(f"======={l}=======")
    print(GSE165291[GSE165291.obs.perturbation_name == l].obs.condition.unique())

=======nan=======
[], Categories (0, object): []
=======CLYBL=======
['control']
Categories (1, object): ['control']
=======US11-US12=======
['control']
Categories (1, object): ['control']
=======US6-US7=======
['control']
Categories (1, object): ['control']
=======US3-US6=======
['control']
Categories (1, object): ['control']
=======AAVS1=======
['control']
Categories (1, object): ['control']
=======H11=======
['control']
Categories (1, object): ['control']
=======TIGRE=======
['control']
Categories (1, object): ['control']
=======US9-US10=======
['control']
Categories (1, object): ['control']

In [21]:
GSE165291.obs.crispr_type.value_counts()

crispr_type
CRISPRn    55388
CRISPRi    46282
Name: count, dtype: int64